import { workflow, node, trigger, ifElse } from '@n8n/workflow-sdk';
const PG = { postgres: { id: 'Zu4Y9UuzGwCBN8lH', name: 'fts-suite-db · fts_admin' } };
const GRAPH = { oAuth2Api: { id: 'Mh5kBNduMzOl3nzT', name: 'Microsoft Graph - sales' } };
const cron = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.2, config: { name: 'Cron cada 5 min 7 a 21', parameters: { rule: { interval: [ { field: 'cronExpression', expression: '*/5 7-21 * * *' } ] } } } });
const manual = trigger({ type: 'n8n-nodes-base.manualTrigger', version: 1, config: { name: 'Manual' } });
const config = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Postgres - Config', credentials: PG, parameters: { operation: 'executeQuery', query: "SELECT retardos.cfg('hojas_carpeta') AS carpeta", options: {} } } });
const hayCarpeta = ifElse({ version: 2.2, config: { name: 'IF - Hay carpeta?', parameters: { conditions: { options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' }, conditions: [ { leftValue: "={{ !!($json.carpeta && $json.carpeta.drive_id && $json.carpeta.folder_id) }}", operator: { type: 'boolean', operation: 'true', singleValue: true } } ], combinator: 'and' } } } });
const listar = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'HTTP - Graph listar carpeta', credentials: GRAPH, alwaysOutputData: true, onError: 'continueRegularOutput', parameters: { method: 'GET', url: "={{ 'https://graph.microsoft.com/v1.0/drives/' + $json.carpeta.drive_id + '/items/' + $json.carpeta.folder_id + '/children' }}", authentication: 'genericCredentialType', genericAuthType: 'oAuth2Api', sendQuery: true, queryParameters: { parameters: [ { name: '$top', value: '50' } ] }, options: {} } } });
const archivos = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - Archivos de la carpeta', parameters: { mode: 'runOnceForAllItems', jsCode: __ARCHIVOS__ } } });
const bajar = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'HTTP - Graph bajar archivo', credentials: GRAPH, onError: 'continueRegularOutput', parameters: { method: 'GET', url: "={{ 'https://graph.microsoft.com/v1.0/drives/' + $json.drive_id + '/items/' + $json.item_id + '/content' }}", authentication: 'genericCredentialType', genericAuthType: 'oAuth2Api', options: { batching: { batch: { batchSize: 1, batchInterval: 1500 } }, response: { response: { responseFormat: 'file', outputPropertyName: 'data' } } } } } });
const aB64 = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - A base64', parameters: { mode: 'runOnceForAllItems', jsCode: __REGISTRAR__ } } });
const registrar = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Postgres - Registrar hoja', credentials: PG, parameters: { operation: 'executeQuery', query: 'SELECT retardos.hoja_registrar($1::jsonb) AS r', options: { queryReplacement: '={{ JSON.stringify($json.payload) }}' } } } });
const moverSi = ifElse({ version: 2.2, config: { name: 'IF - Mover a procesados?', parameters: { conditions: { options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' }, conditions: [ { leftValue: "={{ $json.r && $json.r.ok === true && !!$('Code - A base64').item.json.procesados_id }}", operator: { type: 'boolean', operation: 'true', singleValue: true } } ], combinator: 'and' } } } });
const mover = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'HTTP - Graph mover a procesados', credentials: GRAPH, onError: 'continueRegularOutput', parameters: { method: 'PATCH', url: "={{ 'https://graph.microsoft.com/v1.0/drives/' + $('Code - A base64').item.json.drive_id + '/items/' + $('Code - A base64').item.json.item_id }}", authentication: 'genericCredentialType', genericAuthType: 'oAuth2Api', sendBody: true, specifyBody: 'json', jsonBody: "={{ JSON.stringify({ parentReference: { id: $('Code - A base64').item.json.procesados_id } }) }}", options: {} } } });
const pendientes = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Postgres - Hojas pendientes', credentials: PG, parameters: { operation: 'executeQuery', query: 'SELECT jsonb_array_elements(retardos.hojas_pendientes(5)) AS h', options: {} } } });
const aBin = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - A binario', parameters: { mode: 'runOnceForAllItems', jsCode: __BINARIO__ } } });
const procesar = node({ type: 'n8n-nodes-base.httpRequest', version: 4.2, config: { name: 'HTTP - Procesador retardos-hojas', onError: 'continueRegularOutput', alwaysOutputData: true, parameters: { method: 'POST', url: 'http://retardos-hojas.railway.internal:8080/leer', sendQuery: true, queryParameters: { parameters: [ { name: 'mime', value: '={{ $json.mime }}' } ] }, sendBody: true, contentType: 'binaryData', inputDataFieldName: 'data', options: { timeout: 180000, batching: { batch: { batchSize: 1, batchInterval: 500 } } } } } });
const resultado = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - Resultado', parameters: { mode: 'runOnceForAllItems', jsCode: __RESULTADO__ } } });
const lectura = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Postgres - Registrar lectura', credentials: PG, parameters: { operation: 'executeQuery', query: 'SELECT retardos.registrar_lectura($1::jsonb) AS r', options: { queryReplacement: '={{ JSON.stringify($json) }}' } } } });
const latido = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Postgres - Latido', credentials: PG, executeOnce: true, parameters: { operation: 'executeQuery', query: 'SELECT retardos.latido($1::jsonb) AS corrida', options: { queryReplacement: "={{ JSON.stringify({ workflow: 'retardos/hojas', ok: true, leidos: $('Code - A binario').all().length }) }}" } } } });
export default workflow('retardos-hojas', 'retardos/hojas')
  .add(cron).to(config)
  .add(manual).to(config)
  .add(config).to(hayCarpeta.onTrue(listar.to(archivos.to(bajar.to(aB64.to(registrar.to(moverSi.onTrue(mover))))))))
  .add(config).to(pendientes).to(aBin).to(procesar).to(resultado).to(lectura).to(latido);
