import { workflow, node, trigger, ifElse } from '@n8n/workflow-sdk';
const PG = { postgres: { id: 'Zu4Y9UuzGwCBN8lH', name: 'fts-suite-db · fts_admin' } };
const ODOO = { odooApi: { id: 'Wansi69xesEqEiY1', name: 'Odoo FTS' } };
const wh = trigger({ type: 'n8n-nodes-base.webhook', version: 2.1, config: { name: 'Webhook', parameters: { httpMethod: 'POST', path: 'rh/dias-mx-usa', responseMode: 'responseNode', options: { allowedOrigins: 'https://yinyo1.github.io' } } } });
const sec = node({ type: 'n8n-nodes-base.set', version: 3.4, config: { name: 'Set - Secreto', parameters: { mode: 'manual', includeOtherFields: false, assignments: { assignments: [ { id: 's1', name: 'secreto', value: '={{ $env.SUITE_JWT_SECRET }}', type: 'string' } ] }, options: {} } } });
const puerta = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - Puerta', parameters: { mode: 'runOnceForAllItems', jsCode: __PUERTA__ } } });
const si = ifElse({ version: 2.2, config: { name: 'IF - Autorizado', parameters: { conditions: { options: { caseSensitive: true, leftValue: '', typeValidation: 'loose' }, conditions: [ { leftValue: '={{ $json.ok }}', operator: { type: 'boolean', operation: 'true', singleValue: true } } ], combinator: 'and' }, looseTypeValidation: true } } });
const emps = node({ type: 'n8n-nodes-base.odoo', version: 1, config: { name: 'Odoo - empleados', credentials: ODOO, alwaysOutputData: true, parameters: { resource: 'custom', customResource: 'hr.employee', operation: 'getAll', returnAll: true, options: { fieldsList: ['id', 'name'] }, filterRequest: { filter: [ { fieldName: 'company_id', operator: 'equal', value: '={{ 1 }}' }, { fieldName: 'active', operator: 'in', value: '={{ [true, false] }}' } ] } } } });
const atts = node({ type: 'n8n-nodes-base.odoo', version: 1, config: { name: 'Odoo - asistencias', credentials: ODOO, executeOnce: true, alwaysOutputData: true, parameters: { resource: 'custom', customResource: 'hr.attendance', operation: 'getAll', returnAll: true, options: { fieldsList: ['id', 'employee_id', 'check_in', 'check_out', 'worked_hours', 'x_studio_manager_approval', 'x_studio_project_id', 'x_studio_many2one_field_GUbBF'] }, filterRequest: { filter: [ { fieldName: 'check_in', operator: 'greaterOrEqual', value: "={{ $('Code - Puerta').first().json.desde_utc }}" }, { fieldName: 'check_in', operator: 'lesserOrEqual', value: "={{ $('Code - Puerta').first().json.hasta_utc }}" } ] } } } });
const ids = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - Ids proyecto', executeOnce: true, parameters: { mode: 'runOnceForAllItems', jsCode: __PROYECTOS__ } } });
const proy = node({ type: 'n8n-nodes-base.odoo', version: 1, config: { name: 'Odoo - proyectos', credentials: ODOO, executeOnce: true, alwaysOutputData: true, parameters: { resource: 'custom', customResource: 'project.project', operation: 'getAll', returnAll: true, options: { fieldsList: ['id', 'company_id'] }, filterRequest: { filter: [ { fieldName: 'id', operator: 'in', value: '={{ $json.proj_ids }}' }, { fieldName: 'active', operator: 'in', value: '={{ [true, false] }}' } ] } } } });
const payload = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - Payload', executeOnce: true, parameters: { mode: 'runOnceForAllItems', jsCode: __PAYLOAD__ } } });
const leer = node({ type: 'n8n-nodes-base.postgres', version: 2.6, config: { name: 'Postgres - Leer', credentials: PG, onError: 'continueRegularOutput', parameters: { operation: 'executeQuery', query: 'SELECT asistencia.leer($1::jsonb) AS filas, asistencia.ultimo_cuadre() AS cuadre', options: { queryReplacement: '={{ JSON.stringify($json.payload) }}' } } } });
const armar = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Code - Reporte', parameters: { mode: 'runOnceForAllItems', jsCode: __ARMAR__ } } });
const ok = node({ type: 'n8n-nodes-base.respondToWebhook', version: 1.5, config: { name: 'Responder', parameters: { respondWith: 'json', responseBody: '={{ JSON.stringify($json) }}', options: {} } } });
const no = node({ type: 'n8n-nodes-base.respondToWebhook', version: 1.5, config: { name: 'Responder 401', parameters: { respondWith: 'json', responseBody: '={{ JSON.stringify({ success: false, error: $json.error }) }}', options: { responseCode: 401 } } } });
export default workflow('rh-dias-mx-usa', 'rh/dias-mx-usa')
  .add(wh).to(sec).to(puerta).to(si.onTrue(emps.to(atts.to(ids.to(proy.to(payload.to(leer.to(armar.to(ok)))))))).onFalse(no));
