// ═══ Wizard — pasos y renderizadores ═══
import { TYPES, MATS, PERFS, FLUIDS, PISOS, PATAS, TAQUETES, ZONAS, EXPOS, D, currentStep, setCurrentStep } from './data.js';
import { esc, sel, inp, tog, field, hintBox, notes } from './utils.js';

export function getSteps(){
  const t=D.tipo_estructura;
  const b=[{id:'tipo',label:'Tipo',icon:'🏛️'},{id:'proyecto',label:'Proyecto',icon:'📋'},{id:'estructura',label:'Estructura',icon:'🏗️'},{id:'cargas',label:'Cargas',icon:'⚖️'}];
  if(t==='tuberia')b.push({id:'tuberia',label:'Tubería',icon:'🔧'},{id:'ariete',label:'Ariete',icon:'💥'});
  if(t==='mezz_equipos'||t==='tanque')b.push({id:'equipos',label:'Equipos',icon:'⚙️'});
  if(t==='polipasto')b.push({id:'izaje',label:'Izaje',icon:'🏗️'});
  if(t==='mezz_personas')b.push({id:'acceso',label:'Acceso',icon:'🚶'});
  b.push({id:'sismo',label:'Sismo/Viento',icon:'🌪️'},{id:'ciment',label:'Cimentación',icon:'🧱'},{id:'fea',label:'FEA',icon:'🔬'},{id:'archivos',label:'Archivos',icon:'📎'},{id:'firmas',label:'Firmas',icon:'✍️'},{id:'resumen',label:'Resumen',icon:'✅'});
  return b;
}

export function upd(k,v){D[k]=v;render()}

export function toggl(k){D[k]=!D[k];render()}

export function selectType(id){D.tipo_estructura=id;setCurrentStep(0);render()}

export function goStep(i){const steps=getSteps();if(i<=currentStep+1&&i<steps.length){setCurrentStep(i);render()}}

export function nextStep(){const steps=getSteps();if(currentStep<steps.length-1){setCurrentStep(currentStep+1);render()}}

export function prevStep(){if(currentStep>0){setCurrentStep(currentStep-1);render()}}

export function renderTipo(){return`<h3 class="t">¿Qué tipo de estructura?</h3><p class="s">Ajusta campos y análisis.</p><div class="type-grid">${TYPES.map(t=>`<div class="tc${D.tipo_estructura===t.id?' sel':''}" onclick="selectType('${t.id}')"><div style="font-size:26px;margin-bottom:4px">${t.icon}</div><div style="font-size:14px;font-weight:700;color:#1a2a3a">${t.label}</div><div style="font-size:11px;color:#7f8c8d;margin-top:2px">${t.desc}</div></div>`).join('')}</div>`}

export function renderProyecto(){return`<h3 class="t">Datos del Proyecto</h3><p class="s">Portada y header Nalco.</p><div class="g2">${field("Cliente",inp(D.cliente,"cliente","Arca Continental"),1)}${field("No. Documento",inp(D.num_documento,"num_documento","SO11547-MC-001"),1,"Sistema del cliente")}</div>${field("Proyecto",inp(D.proyecto,"proyecto","Sistema de remoción de Radium-226"),1)}${field("Nombre Documento",inp(D.nombre_documento,"nombre_documento","Memoria de Cálculo..."))}<div class="g3">${field("Planta",inp(D.ubicacion_planta,"ubicacion_planta","Planta Topo Chico"))}${field("Municipio",inp(D.ubicacion_municipio,"ubicacion_municipio","Monterrey"))}${field("Estado",inp(D.ubicacion_estado,"ubicacion_estado"))}</div>${notes("notas_proyecto","Ej: Cliente requiere formato bilingüe EN/ES...")}`}

export function renderEstructura(){const t=D.tipo_estructura,isMezz=t==='mezz_personas'||t==='mezz_equipos';let h=`<h3 class="t">Configuración Estructural</h3><p class="s">Geometría, materiales y perfiles.</p>`;if(t==='tuberia')h+=hintBox('info','💡','TÍPICO NALCO','HSS 2x2x3/16" o PTR 2"x2" Cal.14 en AISI 304.');if(isMezz)h+=hintBox('info','💡','MEZZANINE','IPR W8x10 mín. vigas. Piso: rejilla Irving 19-W-4.');if(t==='polipasto')h+=hintBox('info','💡','POLIPASTO','Monorriel S6x12.5 o W8x10. Factor impacto 1.25 AISC.');h+=`<div class="sec">Columnas</div><div class="g2">${field("Material",sel(MATS,D.material_columnas,"material_columnas"),1)}${field("Perfil",sel(PERFS,D.perfil_columnas,"perfil_columnas"),1)}</div>`;if(D.material_columnas==='Otro (especificar)')h+=field("Material (otro)",inp(D.material_columnas_otro,"material_columnas_otro","ASTM A588, Duplex 2205..."));if(D.perfil_columnas==='Otro (especificar)')h+=field("Perfil (otro)",inp(D.perfil_columnas_otro,"perfil_columnas_otro","Especificar"));h+=`<div class="g3">${field("No. Columnas",inp(D.num_columnas,"num_columnas","4","number"),1)}${field("Altura (mm)",inp(D.altura_columna_mm,"altura_columna_mm","3000","number"),1)}${field("Config. Patas",sel(PATAS,D.config_patas,"config_patas"))}</div><div class="sec">Vigas Principales</div><div class="g2">${field("Material",sel(MATS,D.material_vigas,"material_vigas"))}${field("Perfil",sel(PERFS,D.perfil_vigas,"perfil_vigas"))}</div>`;if(D.material_vigas==='Otro (especificar)')h+=field("Material (otro)",inp(D.material_vigas_otro,"material_vigas_otro","Especificar"));if(D.perfil_vigas==='Otro (especificar)')h+=field("Perfil (otro)",inp(D.perfil_vigas_otro,"perfil_vigas_otro","Especificar"));if(isMezz||t==='general')h+=`<div class="sec">Sistema de Piso</div><div class="g2">${field("Material Piso",sel(PISOS,D.material_piso,"material_piso"))}${field("Largueros",sel(PERFS,D.perfil_piso,"perfil_piso"))}</div>`;h+=`<div class="sec">Geometría</div><div class="g3">${field("Longitud (mm)",inp(D.longitud_total_mm,"longitud_total_mm","6000","number"))}${field("Ancho (mm)",inp(D.ancho_total_mm,"ancho_total_mm","3000","number"))}${field("Sep. Marcos (mm)",inp(D.separacion_marcos_mm,"separacion_marcos_mm","2000","number"))}</div>`;if(isMezz)h+=`<div class="g2">${field("Niveles",sel(["1","2","3"],D.num_niveles,"num_niveles"))}${field("Entrenivel (mm)",inp(D.altura_entrenivel_mm,"altura_entrenivel_mm","3500","number"))}</div>`;h+=tog(D.usa_arriostres,"usa_arriostres","¿Arriostres?");if(D.usa_arriostres)h+=field("Perfil Arriostres",sel(PERFS,D.perfil_arriostres,"perfil_arriostres"));h+=notes("notas_estructura","Ej: Estructura adosada a muro...");return h}

export function renderCargas(){const t=D.tipo_estructura;const cvH={tuberia:"Solo mantenimiento: 100 kg/m²",mezz_personas:"ASCE 7: 488 kg/m² plataformas industriales",mezz_equipos:"Según equipos + mantenimiento",polipasto:"Según capacidad de izaje",tanque:"Según peso operación",general:"Definir según uso"};let h=`<h3 class="t">Cargas</h3><p class="s">Desglose sobre la estructura.</p><div class="sec">Carga Muerta</div>`;if(t==='tuberia'){h+=`<div class="g2">${field("Tubería (kg)",inp(D.carga_muerta_tuberia_kg,"carga_muerta_tuberia_kg","85","number"))}${field("Agua (kg)",inp(D.carga_muerta_agua_kg,"carga_muerta_agua_kg","120","number"))}${field("Accesorios (kg)",inp(D.carga_muerta_accesorios_kg,"carga_muerta_accesorios_kg","30","number"))}${field("Válvulas (kg)",inp(D.carga_muerta_valvulas_kg,"carga_muerta_valvulas_kg","45","number"))}</div>`;const tot=[D.carga_muerta_tuberia_kg,D.carga_muerta_agua_kg,D.carga_muerta_accesorios_kg,D.carga_muerta_valvulas_kg].reduce((s,v)=>s+(parseFloat(v)||0),0);if(tot>0)h+=`<div class="total"><span class="tl">CM Total/Columna</span><span class="tv">${tot.toFixed(1)} kg</span></div>`}if(['mezz_personas','mezz_equipos','general'].includes(t))h+=`<div class="g2">${field("CM Estructura (kg/m²)",inp(D.carga_muerta_estructura_kg_m2,"carga_muerta_estructura_kg_m2","25","number"))}${field("CM Piso (kg/m²)",inp(D.carga_muerta_piso_kg_m2,"carga_muerta_piso_kg_m2","35","number"))}</div>`;if(['mezz_equipos','tanque'].includes(t))h+=field("Peso Equipos (kg)",inp(D.carga_muerta_equipo_kg,"carga_muerta_equipo_kg","2500","number"),"","Peso operación total");h+=field("Carga/Columna (kg)",inp(D.carga_por_columna_kg,"carga_por_columna_kg","280","number"),"","Dato global");h+=`<div class="sec">Carga Viva</div>`;h+=hintBox('info','💡','REFERENCIA',cvH[t]||'Definir');h+=`<div class="g2">${field("CV (kg/m²)",inp(D.carga_viva_kg_m2,"carga_viva_kg_m2",t==='mezz_personas'?"488":"100","number"),1)}${field("Justificación",inp(D.carga_viva_justificacion,"carga_viva_justificacion","ASCE 7 Table 4.3-1"))}</div>`;if(['polipasto','mezz_equipos','tanque'].includes(t))h+=`<div class="sec">Cargas Puntuales</div><div class="g2">${field("Puntual (kg)",inp(D.carga_puntual_kg,"carga_puntual_kg","5000","number"))}${field("Ubicación",inp(D.carga_puntual_ubicacion,"carga_puntual_ubicacion","Centro de claro"))}</div>`;h+=notes("notas_cargas","Ej: Prueba hidrostática 1.3x...");return h}

export function renderTuberia(){return`<h3 class="t">Datos de Tubería</h3><p class="s">Líneas soportadas.</p><div class="g3">${field("Diámetro (pulg)",inp(D.diametro_tuberia_pulg,"diametro_tuberia_pulg",'4"'),1)}${field("Longitud (m)",inp(D.longitud_tuberia_m,"longitud_tuberia_m","12","number"))}${field("No. Tuberías",inp(D.num_tuberias,"num_tuberias","2","number"))}</div><div class="g2">${field("Fluido",sel(FLUIDS,D.fluido,"fluido"))}${field("Presión (PSI)",inp(D.presion_operacion_psi,"presion_operacion_psi","60","number"))}</div>${notes("notas_tuberia","Ej: Tracing de vapor +15 kg/m...")}`}

export function renderAriete(){let h=`<h3 class="t">Golpe de Ariete</h3><p class="s">Sobrepresión por cierre de válvulas.</p>${tog(D.aplica_ariete,"aplica_ariete","¿Aplica?")}`;if(D.aplica_ariete)h+=hintBox('warn','⚠️','IMPORTANTE','Fuerzas laterales significativas. Datos reales requeridos.')+`<div class="g2">${field("Caudal (l/s)",inp(D.caudal_ls,"caudal_ls","8.5","number"),1)}${field("Tiempo Cierre (seg)",inp(D.tiempo_cierre_seg,"tiempo_cierre_seg","3","number"),1)}${field("Long. Tramo (m)",inp(D.longitud_tramo_m,"longitud_tramo_m","25","number"))}${field("No. Codos",inp(D.num_codos,"num_codos","4","number"))}</div>${field("Ubicación Codos",inp(D.ubicacion_codos,"ubicacion_codos","2 en base, 2 en cabezal"))}${tog(D.tiene_vfd,"tiene_vfd","¿Bomba con VFD?")}${tog(D.extremos_anclados,"extremos_anclados","¿Extremos anclados?")}`;h+=notes("notas_ariete","Ej: Actuador cierre rápido...");return h}

export function renderEquipos(){return`<h3 class="t">Datos del Equipo</h3><p class="s">Equipo que soporta la estructura.</p><div class="g2">${field("Nombre",inp(D.equipo_nombre,"equipo_nombre","Bomba Grundfos CR-45"),1)}${field("Cantidad",inp(D.num_equipos,"num_equipos","1","number"))}</div><div class="g3">${field("Peso Vacío (kg)",inp(D.equipo_peso_kg,"equipo_peso_kg","850","number"))}${field("Peso Operación (kg)",inp(D.equipo_peso_operacion_kg,"equipo_peso_operacion_kg","1200","number"),1,"Equipo+fluido")}${field("Dimensiones",inp(D.equipo_dimensiones,"equipo_dimensiones","1200x800x950"))}</div><div class="g2">${field("Altura CG (mm)",inp(D.equipo_cg_altura_mm,"equipo_cg_altura_mm","450","number"),"","Centro gravedad")}${field("Factor Impacto",inp(D.factor_impacto,"factor_impacto"),"","1.0 estático, 1.5 vibratorio")}</div>${tog(D.equipo_es_vibratorio,"equipo_es_vibratorio","¿Vibratorio?")}${notes("notas_equipos","Ej: Reemplazo cada 5 años...")}`}

export function renderIzaje(){const CMAA=["A — Ligero/Manual (k=1.10)","B — Moderado/Motorizado (k=1.25)","C — Pesado (k=1.35)","D — Severo (k=1.50)","E — Continuo","F — Continuo severo"];return`<h3 class="t">Datos de Izaje</h3><p class="s">Polipasto, monorriel o puente grúa.</p>${hintBox('warn','⚠️','AISC DG7 + CMAA 74','Factor de impacto según clase de servicio. Verificar capacidad vs carga total a izar.')}<div class="sec">Polipasto / Grúa</div><div class="g2">${field("Marca y Modelo",inp(D.marca_modelo_polipasto,"marca_modelo_polipasto","Ej: Yale YK 2000kg"),1)}${field("Capacidad Nominal (kg)",inp(D.capacidad_polipasto_kg,"capacidad_polipasto_kg","2000","number"),1)}</div><div class="g3">${field("Peso Polipasto (kg)",inp(D.peso_polipasto_kg,"peso_polipasto_kg","150","number"),"","Del catálogo")}${field("Clase CMAA",sel(CMAA,D.clase_servicio_cmaa,"clase_servicio_cmaa"))}${field("Tipo Sistema",sel(["monorriel","puente grúa (bridge crane)"],D.tipo_sistema_grua,"tipo_sistema_grua"))}</div><div class="sec">Carga a Izar (desglose)</div>${hintBox('info','💡','PESO TOTAL','P_total = Recipiente vacío + Contenido@condición + Accesorios conectados')}<div class="g2">${field("Peso Recipiente Vacío (kg)",inp(D.peso_recipiente_vacio_kg,"peso_recipiente_vacio_kg","500","number"))}${field("Accesorios Conectados",inp(D.accesorios_conectados,"accesorios_conectados","Tuberías, válvulas, soportes temp."))}</div><div class="g3">${field("Volumen Contenido (lt)",inp(D.contenido_volumen_lt,"contenido_volumen_lt","","number"),"","Si aplica")}${field("Densidad (kg/lt)",inp(D.contenido_densidad,"contenido_densidad"),"","Agua=1.0")}${field("% Llenado en Izaje",inp(D.contenido_porciento_llenado,"contenido_porciento_llenado"),"","100 si lleno")}</div><div class="sec">Estructura del Monorriel</div><div class="g3">${field("Claro Monorriel (mm)",inp(D.claro_monorriel_mm,"claro_monorriel_mm","6000","number"),1)}${field("Recorrido (mm)",inp(D.recorrido_mm,"recorrido_mm","8000","number"))}${field("Altura Izaje (mm)",inp(D.altura_izaje_mm,"altura_izaje_mm","4000","number"))}</div><div class="g2">${field("Perfil Monorriel",sel(["Monorriel S6x12.5","Monorriel S8x18.4","Monorriel W8x10","Monorriel W8x15","W6x16","W6x20","W8x28","Otro"],D.tipo_monorriel,"tipo_monorriel"),1)}${field("Factor Dinámico",inp(D.carga_dinamica_factor,"carga_dinamica_factor"),"","CMAA: A=1.10, B=1.25, C=1.35")}</div>${notes("notas_izaje","Ej: Solo mantenimiento cada 6 meses, no uso continuo. Polipasto manual sin motorizar.")}`}

export function renderAcceso(){let h=`<h3 class="t">Acceso, Barandal, Escalera</h3><p class="s">Seguridad para plataformas.</p><div class="g2">${field("Tipo Piso",sel(PISOS,D.tipo_piso,"tipo_piso"))}${field("Barandal",sel(["Tubo Ø1-1/2\" con rodapié","Tubo Ø1-1/4\" con rodapié","Ángulo L2x2 con rodapié","Otro"],D.tipo_barandal,"tipo_barandal"))}</div>${field("Altura Barandal (mm)",inp(D.altura_barandal_mm,"altura_barandal_mm"),"","OSHA mín. 1067 mm")}${tog(D.tiene_escalera,"tiene_escalera","¿Escalera?")}`;if(D.tiene_escalera)h+=`<div class="g2">${field("Tipo",sel(["Escalera marina","Inclinada 60°","Inclinada 45°","De gato con jaula"],D.tipo_escalera,"tipo_escalera"))}${field("Ancho (mm)",inp(D.ancho_escalera_mm,"ancho_escalera_mm","750","number"))}</div>`;h+=tog(D.tiene_portilla,"tiene_portilla","¿Portilla (swing gate)?")+notes("notas_acceso","Ej: Barandal removible sección norte...");return h}

export function renderSismo(){return`<h3 class="t">Sismo y Viento</h3><p class="s">ASCE 7-10. Sin datos → Monterrey.</p><div class="sec">Sismo</div><div class="g2">${field("Zona",sel(ZONAS,D.zona_sismica,"zona_sismica"))}${field("Coef. Manual",inp(D.coef_sismico_manual,"coef_sismico_manual","Auto si vacío"),"","Solo si lo pide el cliente")}</div>${field("Factor Importancia",sel(["1.0","1.25","1.5"],D.factor_importancia,"factor_importancia"))}<div class="sec">Viento</div><div class="g2">${field("Velocidad (km/h)",inp(D.velocidad_viento_kmh,"velocidad_viento_kmh","139","number"),"","Monterrey: 130-160")}${field("Exposición",sel(EXPOS,D.categoria_exposicion,"categoria_exposicion"))}</div>${notes("notas_sismo_viento","Ej: Interior, sin viento directo...")}`}

export function renderCiment(){let h=`<h3 class="t">Cimentación y Anclaje</h3><p class="s">Concreto, taquetes, placa base.</p><div class="g2">${field("f'c (kg/cm²)",sel(["200","250","300","350"],D.fc_concreto_kgcm2,"fc_concreto_kgcm2"),1)}${field("Taquete",sel(TAQUETES,D.tipo_taquete,"tipo_taquete"))}</div><div class="g3">${field("Ø Taquete",sel(['3/8"','1/2"','5/8"','3/4"','1"'],D.diametro_taquete,"diametro_taquete"))}${field("Empotramiento (mm)",inp(D.longitud_empotramiento_mm,"longitud_empotramiento_mm","65","number"))}${field("Taquetes/Placa",sel(["2","3","4","6","8"],D.num_taquetes_por_placa,"num_taquetes_por_placa"))}</div><div class="sec">Placa Base</div><div class="g2">${field("Espesor (mm)",inp(D.espesor_placa_base_mm,"espesor_placa_base_mm","9.5","number"))}${field("Dimensiones",inp(D.dimensiones_placa_base,"dimensiones_placa_base","200x200"))}</div><div class="sec">Tipo</div>${tog(D.cimenta_en_losa,"cimenta_en_losa","A losa existente")}${tog(D.cimenta_en_dado,"cimenta_en_dado","Dado de concreto")}`;if(D.cimenta_en_dado)h+=field("Dado (LxWxH mm)",inp(D.dimensiones_dado,"dimensiones_dado","400x400x600"));h+=notes("notas_cimentacion","Ej: Losa 15cm, verificar empotramiento...");return h}

export function renderFea(){return`<h3 class="t">Validación FEA / Simulación</h3><p class="s">Resultados de análisis de elemento finito (Fusion 360, ANSYS, SolidWorks, SAP2000).</p>${hintBox('info','🔬','SECCIÓN 11 DEL DOCUMENTO','Las imágenes FEA se incluyen SOLO en la sección de Validación, nunca en portada ni secciones de cálculo.')}<div class="g2">${field("Software Utilizado",sel(["Fusion 360","ANSYS","SolidWorks Simulation","SAP2000","ETABS","STAAD.Pro","Otro"],D.software_fea,"software_fea"))}${field("Esfuerzo Von Mises Máx (MPa)",inp(D.esfuerzo_von_mises_max_mpa,"esfuerzo_von_mises_max_mpa","","number"),"","Del resultado FEA")}</div>${field("Ubicación del Esfuerzo Máximo",inp(D.ubicacion_von_mises,"ubicacion_von_mises","Ej: Base de columna C-02, unión viga-columna norte"))}<div class="sec">Clasificación de Imágenes</div>${hintBox('warn','📌','REGLA DE IMÁGENES','Tipo A (datos crudos) = NO incluir en PDF. Tipo B (planos CAD/3D) = Sección 3. Tipo C (resultados FEA Von Mises) = SOLO Sección 11.')}<div style="display:grid;gap:8px"><div class="chk${D.tiene_img_fea_frontal?' on':''}" onclick="toggl('tiene_img_fea_frontal')"><div class="chk-b">${D.tiene_img_fea_frontal?'✓':''}</div><div><div style="font-size:13px;font-weight:600;color:${D.tiene_img_fea_frontal?'#1e8449':'#2c3e50'}">Vista Frontal Von Mises</div><div style="font-size:11px;color:#7f8c8d">Mapa de calor con escala de colores</div></div></div><div class="chk${D.tiene_img_fea_lateral?' on':''}" onclick="toggl('tiene_img_fea_lateral')"><div class="chk-b">${D.tiene_img_fea_lateral?'✓':''}</div><div><div style="font-size:13px;font-weight:600;color:${D.tiene_img_fea_lateral?'#1e8449':'#2c3e50'}">Vista Lateral / 2D</div><div style="font-size:11px;color:#7f8c8d">Distribución en columnas</div></div></div><div class="chk${D.tiene_img_fea_3d?' on':''}" onclick="toggl('tiene_img_fea_3d')"><div class="chk-b">${D.tiene_img_fea_3d?'✓':''}</div><div><div style="font-size:13px;font-weight:600;color:${D.tiene_img_fea_3d?'#1e8449':'#2c3e50'}">Vista 3D Isométrica</div><div style="font-size:11px;color:#7f8c8d">Perspectiva general del análisis</div></div></div></div>${notes("notas_fea","Ej: Análisis con carga en posición más desfavorable (centro del claro)...")}`}

export function renderArchivos(){const common=[{k:"archivo_planos",l:"Planos con cotas (Tipo B → Sección 3)"},{k:"archivo_render_3d",l:"Render 3D / Isométrico (Tipo B → Sección 3)"},{k:"archivo_cargas",l:"Diagrama de cargas"},{k:"archivo_fea_frontal",l:"FEA Vista Frontal (Tipo C → Sección 11)"},{k:"archivo_fea_lateral",l:"FEA Vista Lateral (Tipo C → Sección 11)"},{k:"archivo_fea_3d",l:"FEA Vista 3D (Tipo C → Sección 11)"}];const extra={mezz_personas:[{k:"archivo_escalera",l:"Escalera/barandal"}],mezz_equipos:[{k:"archivo_datasheet",l:"Datasheet equipo"}],polipasto:[{k:"archivo_polipasto",l:"Ficha técnica polipasto"},{k:"archivo_render_equipo",l:"Render con equipo instalado (Tipo B)"}],tanque:[{k:"archivo_tanque",l:"Datasheet tanque"}]};const all=[...common,...(extra[D.tipo_estructura]||[]),{k:"archivo_extra",l:"Extras"}];return`<h3 class="t">Archivos Adjuntos</h3><p class="s">Marca los que tienes listos. Clasifica por tipo.</p>${hintBox('warn','📌','CLASIFICACIÓN DE IMÁGENES','Tipo A (datos crudos): NO incluir en PDF. Tipo B (planos/renders): Sección 3. Tipo C (FEA Von Mises): SOLO Sección 11.')}<div style="display:grid;gap:8px">${all.map(f=>`<div class="chk${D[f.k]?' on':''}" onclick="toggl('${f.k}')"><div class="chk-b">${D[f.k]?'✓':''}</div><div style="font-size:13px;font-weight:600;color:${D[f.k]?'#1e8449':'#2c3e50'}">${f.l}</div></div>`).join('')}</div>`}

export function renderFirmas(){return`<h3 class="t">Firmas y Revisión</h3><p class="s">Tabla de revisiones.</p><div class="g3">${field("Elaboró",inp(D.elaboro,"elaboro","Ing. Mateo Salazar"),1)}${field("Revisó",inp(D.reviso,"reviso","Ing. Felipe Pérez"),1)}${field("Aprobó",inp(D.aprobo,"aprobo","Ing. Esteban De La Cruz"),1)}</div><div style="display:grid;grid-template-columns:70px 1fr 1fr;gap:0 16px">${field("Rev.",inp(D.rev_numero,"rev_numero"))}${field("Fecha",inp(D.rev_fecha,"rev_fecha","","date"))}${field("Descripción",inp(D.rev_descripcion,"rev_descripcion"))}</div>${field("Notas",`<textarea rows="3" onchange="upd('notas_adicionales',this.value)" placeholder="Condiciones especiales...">${esc(D.notas_adicionales)}</textarea>`)}`}

export function renderResumen(){const tl=TYPES.find(t=>t.id===D.tipo_estructura)?.label||'—';const loc=[D.ubicacion_planta,D.ubicacion_municipio,D.ubicacion_estado].filter(Boolean).join(', ');function row(k,v){const m=!v||String(v).includes('—');return`<div class="sum-row"><span style="color:#7f8c8d">${k}</span><span style="font-weight:600;color:${m?'#e74c3c':'#2c3e50'}">${v||'⚠️'}</span></div>`}function sec(t,rows){return`<div class="sum-sec"><div class="ss-t">${t}</div><div style="background:#f8fafc;border-radius:6px;padding:4px 12px">${rows}</div></div>`}let h=`<h3 class="t">Resumen</h3><p class="s">Verifica antes de exportar.</p>`;h+=sec('General',row('Tipo',tl)+row('Cliente',D.cliente)+row('Proyecto',D.proyecto)+row('Doc',D.num_documento)+row('Ubicación',loc));h+=sec('Estructura',row('Columnas',(D.num_columnas||'—')+'x '+(D.perfil_columnas||'—'))+row('Material',D.material_columnas)+row('Vigas',D.perfil_vigas||'—')+row('Altura',(D.altura_columna_mm||'—')+' mm')+row('Dim.',(D.longitud_total_mm||'—')+' x '+(D.ancho_total_mm||'—')+' mm'));h+=sec('Cargas',row('CV',(D.carga_viva_kg_m2||'—')+' kg/m²')+row('Carga/Col',(D.carga_por_columna_kg||'—')+' kg'));if(D.tipo_estructura==='polipasto')h+=sec('Izaje',row('Polipasto',D.marca_modelo_polipasto||'—')+row('Capacidad',(D.capacidad_polipasto_kg||'—')+' kg')+row('Clase CMAA',D.clase_servicio_cmaa||'—')+row('Monorriel',D.tipo_monorriel||'—')+row('Claro',(D.claro_monorriel_mm||'—')+' mm')+row('Factor Dinámico',D.carga_dinamica_factor||'—'));if(D.software_fea)h+=sec('FEA',row('Software',D.software_fea)+row('Von Mises Máx',(D.esfuerzo_von_mises_max_mpa||'—')+' MPa')+row('Ubicación',D.ubicacion_von_mises||'—'));h+=sec('Firmas',row('Elaboró',D.elaboro)+row('Revisó',D.reviso)+row('Aprobó',D.aprobo));
const nk=['notas_proyecto','notas_estructura','notas_cargas','notas_tuberia','notas_ariete','notas_equipos','notas_izaje','notas_acceso','notas_sismo_viento','notas_cimentacion','notas_fea','notas_adicionales'];const nn=nk.filter(k=>D[k]);if(nn.length)h+=`<div class="sum-sec"><div class="ss-t" style="color:#b7950b">💬 Comentarios (${nn.length})</div><div style="background:#fefef6;border-radius:6px;padding:8px 12px">${nn.map(k=>`<div style="padding:4px 0;border-bottom:1px solid #f0e9c8;font-size:12px"><span style="color:#b7950b;font-weight:600">${k.replace('notas_','').replace('_',' ')}: </span><span style="color:#2c3e50">${esc(D[k])}</span></div>`).join('')}</div></div>`;return h}

export function getCleanData(){return Object.fromEntries(Object.entries(D).filter(([k,v])=>v!==''&&v!==false))}

export function render(){
  const steps=getSteps();const ss=Math.min(currentStep,steps.length-1);currentStep=ss;const cid=steps[ss].id;
  document.getElementById('headerType').textContent=TYPES.find(t=>t.id===D.tipo_estructura)?.label||'';
  document.getElementById('progressBar').innerHTML=steps.map((s,i)=>`<div class="pill${i===ss?' active':i<ss?' done':''}" onclick="goStep(${i})"><div class="pi">${s.icon}</div><div class="pl">${s.label}</div></div>`).join('');
  document.getElementById('stepContent').innerHTML=RENDERERS[cid]();
  document.getElementById('stepCounter').textContent=`${ss+1}/${steps.length}`;
  document.getElementById('btnPrev').disabled=ss===0;
  const fr=document.getElementById('footerRight');
  if(cid==='resumen'){
    fr.innerHTML=`<div style="display:flex;gap:6px;flex-wrap:wrap"><button class="btn btn-s" style="font-size:11px" onclick="goToAnalysis()">🏗️ Generar Análisis</button><button class="btn btn-p" style="font-size:11px" onclick="copyJson()">📋 Copiar</button><button class="btn btn-g" style="font-size:11px" onclick="dlJson()">💾</button><button class="btn btn-g" style="font-size:11px" onclick="toggleJson()">{}</button></div>`;
  }else{
    const canGo=cid==='tipo'?!!D.tipo_estructura:true;
    fr.innerHTML=`<button class="btn btn-p" ${canGo?'':'disabled'} onclick="nextStep()">Siguiente →</button>`;
  }
  document.getElementById('jsonArea').value=JSON.stringify(getCleanData(),null,2);
}

export function copyJson(){
  navigator.clipboard.writeText(JSON.stringify(getCleanData(),null,2)).then(()=>{
    const b=event.target;b.textContent='✓';b.classList.add('btn-ok');b.classList.remove('btn-p');setTimeout(()=>{b.textContent='📋 Copiar';b.classList.remove('btn-ok');b.classList.add('btn-p')},2500);
  }).catch(()=>toggleJson());
}

export function dlJson(){const j=JSON.stringify(getCleanData(),null,2);const a=document.createElement('a');a.href='data:application/json;charset=utf-8,'+encodeURIComponent(j);a.download=(D.num_documento||'FTS-MC')+'.json';a.click()}

export function toggleJson(){const p=document.getElementById('jsonPanel');p.style.display=p.style.display==='none'?'block':'none'}

